'use strict';
const $=id=>document.getElementById(id);
let state=null,kind='tv',activeId='',selected=new Set(),history=[],future=[],dirty=false,busy=false,limit=100,drag=null,toastTimer,demoMode=false;
const draftKey='zgemma-kanaly-robocza-v1';
const clone=x=>JSON.parse(JSON.stringify(x));
const el=(tag,className='',value='')=>{const n=document.createElement(tag);n.className=className;n.textContent=value;return n;};
const current=()=>state?.groups.find(g=>g.id===activeId);
const visibleGroups=()=>state?.groups.filter(g=>g.kind===kind)||[];
function notice(message,error=false){$('toast').textContent=message;$('toast').classList.toggle('error',error);$('toast').hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').hidden=true,error?9000:5000);}
async function api(path,data){const response=await fetch('/api/'+path,{method:data===undefined?'GET':'POST',headers:data===undefined?{}:{'Content-Type':'application/json','X-Kanaly-Editor':'1'},body:data===undefined?undefined:JSON.stringify(data)});let result;try{result=await response.json();}catch(e){throw Error('Dekoder nie odpowiedział poprawnie.');}if(!response.ok){throw Error(result.error||'Nie udało się wykonać operacji.');}return result;}
function setBusy(value){busy=value;renderButtons();}
async function run(fn){if(busy)return;setBusy(true);try{await fn();}catch(e){notice(e.message,true);}finally{setBusy(false);}}
function storeDraft(){try{if(dirty&&state)localStorage.setItem(draftKey,JSON.stringify({revision:state.revision,groups:state.groups}));else localStorage.removeItem(draftKey);}catch(e){}}
function acceptState(data,changed=false){state=data;demoMode=Boolean(data.demo)||demoMode;$('demoBanner').hidden=!demoMode;dirty=changed;history=[];future=[];selected.clear();if(!visibleGroups().some(g=>g.id===activeId))activeId=visibleGroups()[0]?.id||'';$('app').hidden=false;$('startup').hidden=true;render();storeDraft();}
async function load(recover=false){const recovery=localStorage.getItem(draftKey);const data=await api('state');acceptState(data);if(recover){try{const saved=JSON.parse(recovery||'null');if(saved&&saved.revision===data.revision&&Array.isArray(saved.groups)&&saved.groups.every(g=>Array.isArray(g.items)&&g.items.every(id=>data.catalog[id]))){state.groups=saved.groups;dirty=true;render();storeDraft();notice('Przywrócono niezapisaną wersję roboczą z tej przeglądarki.');}}catch(e){}}}
function mutate(fn){if(busy||!state)return;const before=JSON.stringify(state.groups);fn();if(before===JSON.stringify(state.groups))return;history.push(JSON.parse(before));if(history.length>80)history.shift();future=[];dirty=true;selected.clear();render();storeDraft();}
function undo(){if(!history.length||busy)return;future.push(clone(state.groups));state.groups=history.pop();dirty=true;selected.clear();render();storeDraft();}
function redo(){if(!future.length||busy)return;history.push(clone(state.groups));state.groups=future.pop();dirty=true;selected.clear();render();storeDraft();}
function renderButtons(){if(!state)return;$('undo').disabled=busy||!history.length;$('redo').disabled=busy||!future.length;$('save').disabled=busy||!dirty;for(const id of ['reload','import','export','backups','newGroup','renameGroup','deleteGroup'])$(id).disabled=busy;$('changeState').textContent=busy?'Trwa operacja…':dirty?'Niezapisane zmiany':'Lista wczytana';$('changeState').classList.toggle('dirty',dirty);const pick=selected.size>0;for(const id of ['position','remove','copy','move'])$(id).disabled=busy||!pick||(!current());$('confirmSave').disabled=busy;$('restore').disabled=busy||!$('backupSelect').options.length;}
function groupMove(delta){const groups=visibleGroups(),index=groups.findIndex(g=>g.id===activeId),other=groups[index+delta];if(!other)return;mutate(()=>{const i=state.groups.findIndex(g=>g.id===activeId),j=state.groups.findIndex(g=>g.id===other.id);[state.groups[i],state.groups[j]]=[state.groups[j],state.groups[i]];});}
function render(){if(!state)return;const groups=visibleGroups();if(!groups.some(g=>g.id===activeId))activeId=groups[0]?.id||'';$('tv').classList.toggle('active',kind==='tv');$('radio').classList.toggle('active',kind==='radio');$('groupCount').textContent=groups.length;$('groupList').replaceChildren();for(const g of groups){const row=el('div','group-row'+(g.id===activeId?' active':''));row.tabIndex=0;row.setAttribute('role','button');row.dataset.group=g.id;row.draggable=true;row.append(el('span','handle','⠿'),el('span','label',g.name),el('span','count',String(g.items.filter(id=>state.catalog[id]?.type==='channel').length)));row.onclick=()=>{activeId=g.id;selected.clear();render();};row.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();row.click();}};row.ondragstart=e=>{drag={type:'group',id:g.id};e.dataTransfer.setData('text/plain',g.id);};row.ondragover=e=>{if(drag?.type==='group'){e.preventDefault();row.classList.add('drop-target');}};row.ondragleave=()=>row.classList.remove('drop-target');row.ondrop=e=>{e.preventDefault();row.classList.remove('drop-target');if(drag?.type!=='group'||drag.id===g.id)return;const source=drag.id;mutate(()=>{const i=state.groups.findIndex(x=>x.id===source);const [item]=state.groups.splice(i,1);const j=state.groups.findIndex(x=>x.id===g.id);state.groups.splice(j,0,item);});drag=null;};$('groupList').append(row);}
 const g=current();$('groupTitle').textContent=g?.name||'Dodaj pierwszą grupę';$('groupUp').disabled=!g||groups[0]?.id===activeId;$('groupDown').disabled=!g||groups.at(-1)?.id===activeId;$('destination').replaceChildren();for(const target of groups.filter(x=>x.id!==activeId)){const option=el('option','',target.name);option.value=target.id;$('destination').append(option);}renderChannels();renderLibrary();const channels=Object.values(state.catalog).filter(x=>x.type==='channel');$('total').textContent=channels.length+' kanałów w katalogu · '+state.groups.length+' grup';renderButtons();}
function moveItem(index,delta){const g=current();if(!g||index+delta<0||index+delta>=g.items.length)return;mutate(()=>{[g.items[index],g.items[index+delta]]=[g.items[index+delta],g.items[index]];});}
function channelLabel(entry){const label=el('span','name');label.append(el('span','channel-name',entry.name));if(entry.type==='channel')label.append(el('span','channel-genre',entry.genre||'Typ nieokreślony'));return label;}
function renderChannels(){const g=current(),query=$('groupSearch').value.toLocaleLowerCase('pl');$('channelList').replaceChildren();if(!g){$('channelList').append(el('div','empty','Utwórz grupę i dodaj do niej kanały z katalogu.'));return;}let visible=0;g.items.forEach((id,index)=>{const entry=state.catalog[id];if(!entry||!entry.name.toLocaleLowerCase('pl').includes(query))return;visible++;const row=el('div','channel-row'+(selected.has(id)?' selected':'')+(entry.type==='marker'?' marker':''));row.dataset.item=id;row.dataset.index=index;row.draggable=true;const checkbox=document.createElement('input');checkbox.type='checkbox';checkbox.checked=selected.has(id);checkbox.setAttribute('aria-label','Zaznacz '+entry.name);checkbox.onchange=()=>{if(checkbox.checked)selected.add(id);else selected.delete(id);renderChannels();renderButtons();};const label=channelLabel(entry);const controls=el('span','row-actions');for(const [symbol,title,fn,disabled] of [['↑','Przesuń wyżej',()=>moveItem(index,-1),index===0],['↓','Przesuń niżej',()=>moveItem(index,1),index===g.items.length-1],['×','Usuń z tej grupy',()=>mutate(()=>g.items.splice(index,1)),false]]){const button=el('button','',symbol);button.title=title;button.setAttribute('aria-label',title+' '+entry.name);button.disabled=disabled;button.onclick=fn;controls.append(button);}row.append(el('span','number',String(index+1)),checkbox,label,controls);row.ondragstart=e=>{drag={type:'item',id,index,group:g.id};e.dataTransfer.setData('text/plain',id);};row.ondragover=e=>{if(drag&&drag.type!=='group'){e.preventDefault();row.classList.add('drop-target');}};row.ondragleave=()=>row.classList.remove('drop-target');row.ondrop=e=>{e.preventDefault();e.stopPropagation();row.classList.remove('drop-target');dropItem(index);};$('channelList').append(row);});if(!visible)$('channelList').append(el('div','empty',query?'Nie ma kanałów pasujących do wyszukiwania.':'Przeciągnij tu kanał lub kliknij + w katalogu.'));$('selectedCount').textContent=selected.size?'Zaznaczone: '+selected.size:'Zaznacz kanały, aby je przenieść';$('groupFooter').textContent=g.items.filter(id=>state.catalog[id]?.type==='channel').length+' kanałów w grupie'+(query?' · widoczne wpisy: '+visible:'');}
function addItem(id){const g=current();if(!g)return notice('Najpierw utwórz grupę.');if(g.items.includes(id))return;mutate(()=>g.items.push(id));}
function dropItem(position){const g=current(),d=drag;drag=null;if(!g||!d||d.type==='group')return;if(state.catalog[d.id]?.kind!==g.kind)return;if(d.type==='library'){if(g.items.includes(d.id))return;mutate(()=>g.items.splice(position,0,d.id));}else{mutate(()=>{const source=state.groups.find(x=>x.id===d.group);if(!source)return;source.items.splice(d.index,1);if(source===g&&d.index<position)position--;g.items.splice(position,0,d.id);});}}
function renderLibrary(){const query=$('librarySearch').value.toLocaleLowerCase('pl'),g=current(),assigned=new Set(g?.items||[]);const entries=Object.values(state.catalog).filter(x=>x.type==='channel'&&x.kind===kind&&x.name.toLocaleLowerCase('pl').includes(query)&&(!$('onlyMissing').checked||!assigned.has(x.id))).sort((a,b)=>Number(Boolean(a.placeholder))-Number(Boolean(b.placeholder))||a.name.localeCompare(b.name,'pl'));$('libraryCount').textContent=entries.length;$('libraryList').replaceChildren();for(const item of entries.slice(0,limit)){const row=el('div','library-row');row.dataset.library=item.id;row.draggable=true;const button=el('button','',assigned.has(item.id)?'✓':'+');button.title=assigned.has(item.id)?'Już w tej grupie':'Dodaj do wybranej grupy';button.setAttribute('aria-label','Dodaj '+item.name);button.disabled=assigned.has(item.id)||!g;button.onclick=()=>addItem(item.id);row.append(channelLabel(item),button);row.ondragstart=e=>{drag={type:'library',id:item.id};e.dataTransfer.setData('text/plain',item.id);};$('libraryList').append(row);}if(!entries.length)$('libraryList').append(el('div','empty','Nie znaleziono kanałów.'));$('more').hidden=entries.length<=limit;$('more').textContent='Pokaż więcej ('+(entries.length-limit)+')';}
function selectedItems(){return current()?.items.filter(id=>selected.has(id))||[];}
function transfer(move){const g=current(),target=state.groups.find(x=>x.id===$('destination').value),ids=selectedItems();if(!target||!ids.length)return;mutate(()=>{for(const id of ids)if(!target.items.includes(id))target.items.push(id);if(move)g.items=g.items.filter(id=>!selected.has(id));});}
$('tv').onclick=()=>{kind='tv';selected.clear();limit=100;render();};$('radio').onclick=()=>{kind='radio';selected.clear();limit=100;render();};$('undo').onclick=undo;$('redo').onclick=redo;
$('groupSearch').oninput=()=>{selected.clear();renderChannels();renderButtons();};$('librarySearch').oninput=()=>{limit=100;renderLibrary();};$('onlyMissing').onchange=()=>{limit=100;renderLibrary();};$('more').onclick=()=>{limit+=100;renderLibrary();};$('groupUp').onclick=()=>groupMove(-1);$('groupDown').onclick=()=>groupMove(1);
$('newGroup').onclick=()=>{const name=prompt('Nazwa nowej grupy:');if(!name?.trim())return;const id='userbouquet.ke_'+Date.now().toString(16)+Math.random().toString(16).slice(2,8)+'.'+kind;mutate(()=>{state.groups.push({id,name:name.trim(),kind,items:[]});activeId=id;});};
$('renameGroup').onclick=()=>{const g=current();if(!g)return;const name=prompt('Nowa nazwa grupy:',g.name);if(name?.trim())mutate(()=>g.name=name.trim());};
$('deleteGroup').onclick=()=>{const g=current();if(!g)return;if(confirm('Usunąć grupę „'+g.name+'”? Kanały pozostaną w katalogu i innych grupach.'))mutate(()=>state.groups=state.groups.filter(x=>x.id!==g.id));};
$('position').onclick=()=>{const g=current(),ids=selectedItems();if(!g||!ids.length)return;const value=prompt('Pierwsza pozycja dla zaznaczonych kanałów (od 1 do '+g.items.length+'):','1');if(value===null)return;const p=Number(value);if(!Number.isInteger(p)||p<1||p>g.items.length)return notice('Wpisz prawidłowy numer pozycji.',true);mutate(()=>{g.items=g.items.filter(id=>!selected.has(id));g.items.splice(Math.min(p-1,g.items.length),0,...ids);});};
$('remove').onclick=()=>{const g=current();if(g)mutate(()=>g.items=g.items.filter(id=>!selected.has(id)));};$('copy').onclick=()=>transfer(false);$('move').onclick=()=>transfer(true);
$('channelList').ondragover=e=>{if(drag&&drag.type!=='group')e.preventDefault();};$('channelList').ondrop=e=>{e.preventDefault();dropItem(current()?.items.length||0);};document.addEventListener('dragend',()=>{drag=null;document.querySelectorAll('.drop-target').forEach(n=>n.classList.remove('drop-target'));});
$('reload').onclick=()=>{if(dirty&&!confirm('Wczytać listę z dekodera i porzucić niezapisane zmiany?'))return;run(async()=>{await load();notice('Wczytano obecną listę dekodera.');});};
$('import').onclick=()=>{if(dirty&&!confirm('Wczytać paczkę zamiast bieżącej wersji roboczej?'))return;$('file').click();};$('file').onchange=()=>run(async()=>{const file=$('file').files[0];if(!file)return;if(file.size>20*1024*1024)throw Error('Paczka jest za duża.');const data=await new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result).split(',')[1]);reader.onerror=()=>reject(Error('Nie udało się odczytać pliku.'));reader.readAsDataURL(file);});acceptState(await api('import',{data}),true);notice('Paczka wczytana do edycji. Jeszcze nie zapisano jej w dekoderze.');$('file').value='';});
$('export').onclick=()=>run(async()=>{const result=await api('export',{draft:state.draft,groups:state.groups});const bytes=Uint8Array.from(atob(result.data),c=>c.charCodeAt(0));const url=URL.createObjectURL(new Blob([bytes],{type:'application/gzip'}));const a=el('a');a.href=url;a.download=result.filename;a.click();setTimeout(()=>URL.revokeObjectURL(url),2000);notice('Pobrano paczkę z Twoim układem.');});
$('save').onclick=()=>{if(!state)return;const channels=Object.values(state.catalog).filter(x=>x.type==='channel');$('saveSummary').textContent=state.groups.length+' grup · '+channels.length+' kanałów w katalogu. Kanały bez grupy trafią do „Pozostałe kanały”.';$('confirm').showModal();};
$('confirmSave').onclick=()=>run(async()=>{const result=await api('save',{draft:state.draft,groups:state.groups});$('confirm').close();acceptState(result.state);notice('Zapisano na dekoderze. Kopia: '+result.backup);});
$('backups').onclick=()=>run(async()=>{const result=await api('backups');$('backupSelect').replaceChildren();for(const name of result.backups){const option=el('option','',name);option.value=name;$('backupSelect').append(option);}if(!result.backups.length)return notice('Kopie pojawią się po pierwszym zapisie.');$('backupDialog').showModal();});
$('restore').onclick=()=>{const name=$('backupSelect').value;if(!name||!confirm('Przywrócić wybraną kopię? Zastąpi to bieżącą listę dekodera.'))return;run(async()=>{const result=await api('restore',{name});$('backupDialog').close();acceptState(result.state);notice('Przywrócono wybraną kopię.');});};
document.addEventListener('keydown',e=>{if(['INPUT','SELECT','TEXTAREA'].includes(document.activeElement?.tagName))return;if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='z'){e.preventDefault();e.shiftKey?redo():undo();}if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='y'){e.preventDefault();redo();}});
window.addEventListener('beforeunload',e=>{if(dirty){e.preventDefault();e.returnValue='';}});
async function start(){ $('retry').hidden=true; $('startupMessage').textContent='Wczytuję listę kanałów…'; try{await load(true);}catch(e){$('app').hidden=true;$('startup').hidden=false;$('startupMessage').textContent=e.message;$('retry').hidden=false;}}
$('retry').onclick=start;
start();
